version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: rxjs
    versions:
    - 6.6.6
