export const Actions = {
    "sendMessage": "SEND_MESSAGE" as "SEND_MESSAGE",
    "setIsBusy": "SET_IS_BUSY" as "SET_IS_BUSY",
    "setIsNotBusy": "SET_IS_NOT_BUSY" as "SET_IS_NOT_BUSY",
    "setPaletteSize": "SET_PALETTE_SIZE" as "SET_PALETTE_SIZE",
    "setSourceContents": "SET_SOURCE_CONTENTS" as "SET_SOURCE_CONTENTS",
    "setSourceFile": "SET_SOURCE_FILE" as "SET_SOURCE_FILE",
    "setSourceHistogram": "SET_SOURCE_HISTOGRAM" as "SET_SOURCE_HISTOGRAM",
    "setSourcePalette": "SET_SOURCE_PALETTE" as "SET_SOURCE_PALETTE",
    "setSourcePaletteItem": "SET_SOURCE_PALETTE_ITEM" as "SET_SOURCE_PALETTE_ITEM",
    "setSourcePaletteMap": "SET_SOURCE_PALETTE_MAP" as "SET_SOURCE_PALETTE_MAP",
    "setSourcePath": "SET_SOURCE_PATH" as "SET_SOURCE_PATH",
    "setSourcePixels": "SET_SOURCE_PIXELS" as "SET_SOURCE_PIXELS",
    "setSourcePreviewUrl": "SET_SOURCE_PREVIEW_URL" as "SET_SOURCE_PREVIEW_URL",
    "setSourceProgress": "SET_SOURCE_PROGRESS" as "SET_SOURCE_PROGRESS",
    "setTargetContents": "SET_TARGET_CONTENTS" as "SET_TARGET_CONTENTS",
    "setTargetPalette": "SET_TARGET_PALETTE" as "SET_TARGET_PALETTE",
    "setTargetPaletteItem": "SET_TARGET_PALETTE_ITEM" as "SET_TARGET_PALETTE_ITEM",
    "setTargetPreviewUrl": "SET_TARGET_PREVIEW_URL" as "SET_TARGET_PREVIEW_URL",
    "setTargetProgress": "SET_TARGET_PROGRESS" as "SET_TARGET_PROGRESS",
};
